<?php

namespace NTE\BogartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotaniqueTaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotaniqueTaxonRepository extends EntityRepository
{
    
}
