#nte_bogart:
#    resource: "@NTEBogartBundle/Controller/"
#    type:     annotation
#    prefix:   /

_homepage:
    pattern:   /
#    defaults:  { _controller: SonataAdminBundle:Core:dashboard }
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: parcours2, permanent: true, _locale: fr }

#_import:
#    pattern:   /_import
#    defaults: { _controller: NTEBogartBundle:Import:index }

bogart:
    requirements: # new
        _locale: fr|de # new
    pattern:   /bogart/{_locale}
    defaults: { _controller: NTEBogartBundle:Default:index, _locale: fr }

search:
    requirements: # new
        _locale: fr|de # new
    pattern:   /{_locale}/search
    defaults: { _controller: NTEBogartBundle:Search:index }

search_page_2:
    requirements: # new
        _locale: fr|de # new
    pattern:   /{_locale}/search/{search}/{page}
    defaults: { _controller: NTEBogartBundle:Search:index }

search_page:
    requirements: # new
        _locale: fr|de # new
    pattern:   /{_locale}/search/{page}
    defaults: { _controller: NTEBogartBundle:Search:index }

taxon:
    requirements: # new
        _locale: fr|de # new
    pattern:   /{_locale}/taxon
    defaults: { _controller: NTEBogartBundle:BotaniqueTaxon:index }

taxon_page:
    requirements: # new
        _locale: fr|de # new
    pattern:   /{_locale}/taxon/{page}
    defaults: { _controller: NTEBogartBundle:BotaniqueTaxon:index }

taxon_show:
    requirements: # new
        _locale: fr|de # new
    pattern:   /{_locale}/taxon/{id}/show
    defaults: { _controller: NTEBogartBundle:BotaniqueTaxon:show }

parcours:
    pattern:   /parcours
    defaults: { _controller: NTEBogartBundle:Parcours:index }

parcours1:
    pattern:   /parcours/
    defaults: { _controller: NTEBogartBundle:Parcours:index }

parcours2:
    requirements: # new
        _locale: fr|de # new
    pattern:   /parcours/{_locale}
    defaults: { _controller: NTEBogartBundle:Parcours:index }

parcours3:
    requirements: # new
        _locale: fr|de # new
    pattern:   /parcours/{_locale}/
    defaults: { _controller: NTEBogartBundle:Parcours:index }

parcours_show:
    requirements: # new
        _locale: fr|de # new
    pattern:   /parcours/{_locale}/{id}
    defaults: { _controller: NTEBogartBundle:Parcours:show }

parcours_taxon:
    requirements: # new
        _locale: fr|de # new
    pattern:   /parcours/{_locale}/taxon/{numero}
    defaults: { _controller: NTEBogartBundle:Parcours:showTaxon }

parcours_taxon2:
    requirements: # new
        _locale: fr|de # new
    pattern:   /parcours/{_locale}/taxon/
    defaults: { _controller: NTEBogartBundle:Parcours:showTaxon }

parcours_list:
    requirements:
        _locale: fr|de
    pattern:   /parcours/list/{_locale}
    defaults: { _controller: NTEBogartBundle:Parcours:list }

parcours_list2:
    requirements:
        _locale: fr|de
    pattern:   /parcours/list/{_locale}/
    defaults: { _controller: NTEBogartBundle:Parcours:list }

_rename_taxons:
    pattern:   /admin/_rename_taxons/{start}
    defaults: { _controller: NTEBogartBundle:Default:renameTaxons }

_rename_familles:
    pattern:   /admin/_rename_familles
    defaults: { _controller: NTEBogartBundle:Default:renameFamilles }

_rename_taxons_2:
    pattern:   /admin/_rename_taxons_2/{start}
    defaults: { _controller: NTEBogartBundle:Default:renameTaxons2 }


# test appcache
appcache:
    pattern:    /parcours/bogart.appcache
    defaults: { _controller: NTEBogartBundle:Parcours:appcache }
