<?php

namespace NTE\BogartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotaniqueBiblioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotaniqueBiblioRepository extends EntityRepository
{

    /**
     * {@inheritDoc}
     *
     * @return array The entities.
     */
    public function findBy(array $criteria, array $orderBy = array('titre' => 'asc', 'auteur1' => 'asc', 'maison' => 'asc', 'annee' => 'asc', 'edition' => 'asc', 'isbn' => 'asc'), $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }
}
