<?php

namespace NTE\BogartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotaniqueCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotaniqueCollectionRepository extends EntityRepository
{
#    public function getAccessionFournisseur()
    public function getProvenance()
    {
        return $this->createQueryBuilder('Accession a')
            ->select('a.provenance')
            ->where('a.annee = $this->annee ADN a.numero = $this->numero')
            ->setMaxResults(1)."=====";
    }
}
