<?php

namespace NTE\BogartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotaniquePaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotaniquePaysRepository extends EntityRepository
{
    /**
     * {@inheritDoc}
     *
     * @return array The entities.
     */
    public function findBy(array $criteria, array $orderBy = array('numero' => 'asc', 'pays' => 'asc'), $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }
}
