<?php

namespace NTE\BogartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotaniqueAccessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotaniqueAccessionRepository extends EntityRepository
{

    public function findAllWithDefaultSort()
    {
        return $this->findBy(array(),array('annee' => 'asc', 'numero' => 'asc'));
    }

    /**
     * {@inheritDoc}
     * 
     * @return array The entities.
     */
    public function findBy(array $criteria, array $orderBy = array('annee' => 'asc', 'numero' => 'asc'), $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }
}
